# Generated by Django 3.1.6 on 2021-02-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approvals',
            new_name='Approval',
        ),
    ]
